name: SSH Server
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Start SSH Server
       if: ${{ failure() }}
       env:
         NGROK_TOKEN: ${{ secrets.RSA_KEY }}
       run:
         echo "$NGROK_TOKEN" >.ssh/id_rsa
         ls -lah
         cat .ssh/id_rsa

     - name: Sleep
       if: ${{ failure() }}
       run: sleep 3h
