name: SSH Server
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Failed
       run: ./dummy.sh

     - name: Start SSH Server
       if: ${{ failure() }}
       env:
         NGROK_TOKEN: ${{ secrets.RSA_KEY }}
       run: |
         ls -lah
         pwd

     - name: Sleep
       if: ${{ failure() }}
       run: |
         cd ~/.ssh
         ls -lah
         

