on: [push] # 触发工作流的事件，这里为推送事件，可根据需要调整

jobs:
  setup-wireguard:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install WireGuard
      run: |
        apt update
        apt install -y wireguard
        whoami
        sudo passwd $(whoami) << EOD
        runner
        runner
        EOD

    - name: Setup WireGuard Configuration
      env:
        ADDRESS: ${{ secrets.ADDRESS }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      run: |
        mkdir -p /etc/wireguard
        printf "[Interface]\nAddress = %s\nPrivateKey = %s\n\n[Peer]\nEndpoint = %s\nPublicKey = %s\nAllowedIPs = 172.17.20.0/24\n" \
        "$ADDRESS" "$PRIVATE_KEY" "$SERVER_IP" "$PUBLIC_KEY" > /etc/wireguard/wg0.conf

    - name: Start WireGuard
      run: |
        wg-quick up wg0

    - name: Sleep for 6 hours
      run: |
        sleep 21600

         

