name: SSH Server

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
          cat ~/.ssh/config

      - name: Change user password (optional)
        run: |
          whoami
          sudo passwd $(whoami) << EOD
          runner
          runner
          EOD

      - name: Run dummy script
        run: |
          ./dummy.sh

      - name: Start SSH Server
        if: failure()
        run: |
          ssh -NCfgR 62022:127.0.0.1:22 staging

      - name: Sleep
        if: failure()
        run: |
          sleep 6h
